Mergifyio/mergify-cli

.github/workflows/ci.yaml
=> fix: remove pyoxidizer relica

mergify_cli/__init__.py
Mergify-cli stack change-Id: Ifb0cff2112eeae27d172e0ff3160812b4e5f6180:
=> fix: convert coroutine to task

mergify_cli/__init__.py
Mergify-cli stack change-Id: I35eff5ee0da1b892deaa3ad5a73e168ccf064032:
=> feat: Add control on draft or open status through a param

mergify_cli/__init__.py
Mergify-cli stack change-Id: I4c7f0cf56f847295cec61130d9babf96da314ec9:
=> feat: Define trunk through param --trunk/-t or git config mergify-cli.stack-trunk

mergify_cli/__init__.py
The option was not doing what it said.
They is no point to change the draft status once the PR has been
submitted.
This was changing the draft status set in GitHub UI each time we run
Mergify cli
Now we only set the draft status when a PR is created as the doc string
say.
=> fix: make create as draft, only create as draft

.github/workflows/release.yml
I have already setup the pypi side.
Fixes MRGFY-2430
=> ci: add pypi release workflow

README.md
Make them clearer.
Change-Id: I63950a40dce7028fdbec88091480714750c86ca3
Depends-On: #210
=> docs(readme): update usage steps

mergify_cli/__init__.py
This has been removed by 728137a. The change has added a new git config
key but remove the default setting git use to track upstream branch.
This restore the default, so `mergify-cli stack` will have the same
default as `git push` and `git pull`.
=> feat: set default for --trunk

mergify_cli/__init__.py
Change-Id: I1208b65445387c8bff5f8a70df8767d8583ef32c
=> feat: add hint when Change-Id is not set

README.md
Change-Id: Id51c108f1de893f1c5de2031197b77d1b222b27d
=> docs: add stack command

pyproject.toml
we need to add readme in poetry tools to allow PyPi to load the project
=> chore(poetry): add readme in poetry tools

pyproject.toml
Some data might be missing in order to build PyPi distrib
=> chore(poetry): update toml

.github/workflows/release.yml
in order to test the GHA, we added a workflow dispatch
=> chore(workflow): add dispatch for testing

poetry.lock, pyproject.toml, version_plugin.py
In order to update the version at each push on
PyPi, we needed to use a poetry plugin
=> chore(poetry): add version plugin

.github/workflows/release.yml
Reverts Mergifyio/mergify-cli#258
=> Revert "chore(workflow): add github token"

.mergify.yml
=> ci(mergify): remove schedule

.mergify.yml
This updates the configuration to the latest standards.
=> ci(mergify): update config

mergify_cli/__init__.py
Change-Id: Ib570059d9cac586c84d2ca099de19614f741f112
=> feat: display version

mergify_cli/tests/test_mergify_cli.py
Change-Id: I9cc71c8f66907f4a31c826f4abf07c9e9d504715
=> test: change working directory

mergify_cli/tests/test_mergify_cli.py, mergify_cli/tests/utils.py, poetry.lock, pyproject.toml
Fixes MRGFY-2380
Change-Id: I8f9e753e38e27d9d5460ebb17b368ef1f5fd3696
=> test: add some tests on `stack()`

mergify_cli/__init__.py, mergify_cli/tests/test_mergify_cli.py
Fixes MRGFY-2869
Change-Id: Iff0cbba91116d461cd2efbc5923d073bd8a694f8
=> feat: add a positional indicator in the stack comment

mergify_cli/__init__.py
Change-Id: I747c9b712869256475e72ed85192235b19a18ed7
=> chore: type GitHub comments

.github/dependabot.yml, .github/workflows/ci.yaml, .github/workflows/release.yml
Update all action versions to the latest.
Setup Dependabot to update action versions.
Set the Python version used in actions to the same range as the pyproject.toml file.
Change-Id: Ic3e75f805c75569673a788b449091a37d67497c0
=> ci: update action versions

mergify_cli/tests/test_mergify_cli.py
Change-Id: I5cd81d18b4c7e9c55f0e574b1feb0768f145c7ec
=> test: add coverage on PR content

mergify_cli/tests/test_mergify_cli.py, mergify_cli/tests/utils.py
Change-Id: Ibbe59fe3142f05896f792d19a45792c8195e043b
Depends-On: #335
=> test: abstract commits with GitMock

mergify_cli/__init__.py
Create a StackComment class to encapsulate some functions and a constant.
Depends-On: #362
=> refactor: create StackComment class

mergify_cli/__init__.py, mergify_cli/tests/test_mergify_cli.py
People may edit pull request title and description on GitHub.
mergify stack always erase them.
This change adds an option to never edit them.
=> feat: allow to keep previous title+body

mergify_cli/__init__.py, poetry.lock, pyproject.toml
=> build(deps-dev): Bump ruff from 0.3.7 to 0.4.2

.mergify.yml
Change-Id: I635fa22f9ff2f6db0af008e2ad21b415228dfcf7
=> ci(Mergify): always post success for changelog

mergify_cli/__init__.py, mergify_cli/tests/test_mergify_cli.py, pyproject.toml
Change-Id: I3a795a3cefcff7763a371bb15327bd07d786d707
=> fix: do not ignore S602

mergify_cli/__init__.py, mergify_cli/tests/test_mergify_cli.py, mergify_cli/tests/utils.py
Change-Id: Ie3cc6ddc1b650fdc18c9d6c8b84190e0cb4bab7f
=> fix: do not spawn subshell for git

mergify_cli/__init__.py, mergify_cli/tests/test_mergify_cli.py
Change-Id: I594a5018b7b7d85b7c5e0e71f2beecdb778e4ef3
=> refactor: use asyncio subprocess everywhere

mergify_cli/__init__.py, poetry.lock, pyproject.toml
=> build(deps-dev): Bump ruff from 0.4.3 to 0.4.4

mergify_cli/__init__.py, mergify_cli/tests/utils.py
Otherwise git will output the quote to stdout.
=> fix: don't escape format string

mergify_cli/__init__.py, mergify_cli/tests/test_mergify_cli.py
=> chore: remove deadcode

.mergify.yml
Remove some checks thanks to merge protections.
=> chore(mergify): remove some checks

mergify_cli/__init__.py
=> chore: prefer removesuffix

mergify_cli/__init__.py
This allows to have a stack with some WIP commits, after some already
existing pull requests, that we do not want pushed to a pull request.
=> feat: add argument to only update existing pull requests

mergify_cli/__init__.py
=> fix: add missing space between title and url

mergify_cli/__init__.py, mergify_cli/github_types.py
Change-Id: I25e55b123dc39a1898382a01724d136d03a94f9c
=> refactor: split GitHub types in their own module

mergify_cli/__init__.py, mergify_cli/github_types.py
Change-Id: I3c1c7c97490708253785a8c44650f59bff0a163b
Depends-On: #486
=> refactor: remove unused global vars

mergify_cli/__init__.py
The number of inflight variables is huge.
This change introduce a dataclass to each stack changes.
It makes code more readable and avoid passing a lot of variables around.
=> chore: add some datastructure

mergify_cli/__init__.py
This hides some logic inside a dedicated method.
=> refactor: move retrieval of change IDs and pull inside get_remote_changes()

mergify_cli/__init__.py
We pick the last 7 chars instead of the first 7.
Depends-On: #508
=> fix: all short sha are wrong

mergify_cli/__init__.py
This is required to find the stacked pull request if the stack is not
owned by the owner of the token.
This will be leverage to run mergify-cli inside an GitHub action.
=> feat: allow to pass author

mergify_cli/__init__.py, mergify_cli/tests/test_mergify_cli.py
=> chore: change default branch_prefix

.github/workflows/release.yml, pyproject.toml
poetry-version-plugin is deprecated
=> build: replace poetry-version-plugin by poetry-dynamic-versioning

mergify_cli/stack/changes.py, mergify_cli/stack/push.py, mergify_cli/tests/stack/test_setup.py, poetry.lock, pyproject.toml
=> build(deps-dev): Bump ruff from 0.8.0 to 0.8.3

mergify_cli/stack/changes.py
=> fix(stack): --only-update-existing-pulls handling

mergify_cli/ci/detector.py, mergify_cli/ci/junit.py, mergify_cli/tests/ci/test_junit.py
They will be used to match tests with a GitHub job
=> chore: add new attributes

mergify_cli/ci/upload.py, mergify_cli/tests/ci/test_upload.py
=> refactor: remove notice usage from GHA

mergify_cli/ci/cli.py, mergify_cli/ci/quarantine.py, mergify_cli/tests/ci/test_check_failing_spans.py, mergify_cli/tests/ci/test_cli.py
=> refactor: rename `check_failing_spans_with_quarantine`

mergify_cli/ci/detector.py, mergify_cli/tests/ci/test_detector.py
=> fix(jenkins): get git branch correctly

mergify_cli/ci/cli.py, mergify_cli/tests/ci/test_cli.py
=> fix: handle correctly quarantine errors

.github/workflows/ci.yaml
=> chore(ci-insights): Enable new flaky test detections
