Mergifyio/mergify-cli

README.md

- The `git config --add` command line is missing a `-` according [to this](https://github.com/Mergifyio/mergify-cli/blob/80e851a8690e1300cbd0075df2d676f4a28a3f89/mergify_cli/__init__.py#L402).
- The link to the GitHub client site is not displayed properly.

docs: Fix the config command and a link

---

README.md
mergify_cli/__init__.py

This tool will not be just a stack pr tool.
So we need to define subparsers to allow future commands.
This change uses `stack` argument for the parser.
If no parser is passed we also use `stack` by default to not break
backward compatibility.

feat: add stack subparser

---

README.md

Command options were not the same as the PyPI package options. As the
README is the official documentation of the package, we have to be
consistent. We will have to update the options once the PyPI package is
updated (automatically?).
Change-Id: Icb29c81d51828785766078a34892d9a91df15367
Related to [MRGFY-2430](https://linear.app/mergify/issue/MRGFY-2430/mergify-cli-automatic-publish-on-pypi)

docs(readme): update command options

---

.github/workflows/release.yml

We must double the * to match branch with namespaces (eg: /)

ci: fix branches-ignore

---

.github/workflows/release.yml

disable twine artifact checking before upload to PyPi

chore(workflow): disable metadata checks

---

mergify_cli/__init__.py

This will avoid:
```
$ mergify
Traceback (most recent call last):
File "/Users/sileht/.local/bin/mergify", line 8, in <module>
sys.exit(cli())
^^^^^
File "/Users/sileht/.local/pipx/venvs/mergify-cli/lib/python3.12/site-packages/mergify_cli/__init__.py", line 746, in cli
asyncio.run(args.func(args))
^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'func'
```

fix: set default action correctly

---

mergify_cli/__init__.py
mergify_cli/tests/test_mergify_cli.py

The change ID is stored in the commit message and in the GitHub HEAD branch name. We can remove it from the pull request description to make it prettier.
Change-Id: I56e44be6d6aff6de89d80e1f649568c2c199406c

feat: remove the change ID from the PR description

---

mergify_cli/__init__.py
mergify_cli/tests/test_mergify_cli.py

Don't create a stack comment if the stack contains only one pull request, it's not a stack.

feat: don't create a stack comment for a single PR

---

mergify_cli/__init__.py
mergify_cli/tests/test_mergify_cli.py
mergify_cli/tests/utils.py

When pull request are ready to be merged or queued in a merge
queue, rebasing the stack may unqueue the pull request or removed
approvals.
This change adds an option to not rebase the stack and just update it.

feat: allow to not rebase the stack

---

mergify_cli/__init__.py
mergify_cli/tests/test_mergify_cli.py
mergify_cli/tests/utils.py

This branch does not need to be synced remotely.
This change instead creates a temporary branch for commit and push this one.

chore: don't push the aio branch

---

mergify_cli/__init__.py

GitHub may return 422 before it finishes to read the request body.
This change makes our logging working when this occurs.

fix: handle correctly when client side error without body request read

---

mergify_cli/__init__.py
mergify_cli/tests/test_mergify_cli.py

Parameter `--keep-pull-request-title-and-body` can now have its default value stored in git config as well.
Added help message to indicate that to users regarding former default parameters as well.
Fixes MRGFY-3520

feat(cli): add a config parameter for keep-pr-title-body

---

mergify_cli/__init__.py
mergify_cli/tests/test_mergify_cli.py
pyproject.toml

The current code forces the user to choose a single target branch which
prevents stacks from working on multiple target branches. This leverage
the standard git configuration to retrieve the target branch.
Change-Id: Ia1455d68eaa76af503b6e6cf4c24c19efcdd9b7b

feat: detect target branch using standard Git configuration

---

mergify_cli/__init__.py
mergify_cli/tests/test_mergify_cli.py

If --keep-pull-request-title-and-body is used, body was not updated.
If a dependant PR is closed/deleted, the depends-on is not removed.
Even if the option intent is to keep the PR description as-is. But
mergify cli should continue to manage the Depends-On to avoid issues.

fix: always manage depends-on

---

mergify_cli/__init__.py
mergify_cli/tests/test_mergify_cli.py

In `git `<branch>` --set-upstream-to=<target_remote>/<target_branch>`:
* `target_remote` is `git config branch.<branch>.remote`
* `target_branch` is `git config branch.<branch>.merge`
Before this change, the code was getting the `target_remote` from `git config branch.<target_branch>.remote` which is wrong.

fix: correctly get the target remote

---

mergify_cli/__init__.py
mergify_cli/tests/test_mergify_cli.py
mergify_cli/tests/utils.py

This adds `mergify stack edit` to interactively rebase the stack.
Add `mergify stack` becomes `mergify stack push`
`mergify stack push` being the default when `mergify` or `mergify stack`
is used.

feat: add helper to interactively rebase the stack

---

mergify_cli/__init__.py

We pick the last 7 instead of first 7 chars

fix: correctly build short sha

---

mergify_cli/__init__.py
mergify_cli/github_types.py
mergify_cli/tests/test_mergify_cli.py

If skip-rebase is used, and first PR of the stack is merged, we recreate
it because the pull request has vanish remotely.
This doesn't make sense, this change instead mark it locally as merged.
The merged status will displayed in cli output until the next rebase.
This avoids creating useless PR.

fix: don't recreate merged PR

---

mergify_cli/__init__.py

This will help to do/display the same thing in the dry-run and the
effective run.

refactor: pre compute the action to do for each change of the stack

---

mergify_cli/__init__.py
mergify_cli/github_types.py
mergify_cli/tests/test_mergify_cli.py

Using Git database API does not work for merged PR as the reference of
the deleted branch vanish faster.
This leverages the search API instead.

chore: use a more reliable solution to get changes

---

mergify_cli/__init__.py

GitHub randomly returns None or ""
Depends-On: #520

fix: handle correctly when body is empty

---

mergify_cli/__init__.py
mergify_cli/github_types.py
mergify_cli/tests/test_mergify_cli.py
mergify_cli/tests/utils.py

This new command allows to download a stack.
This will be used by the autorebase GitHub action.

feat: add stack checkout

---

.github/workflows/release.yml
pyproject.toml

build: publish release on GitHub too

---

.github/workflows/release.yml

Release script is failing, asking to set the GH_TOKEN env variable to use gh CLI. This adds it in the step.
https://cli.github.com/manual/gh_auth_login

fix(release): add gh token to env

---

mergify_cli/cli.py
mergify_cli/stack/cli.py

Without a callable the defaults are evaluated on import which causes unexpected errors with other commands.

fix(chore): use a callable for defaults

---

mergify_cli/ci/junit_upload.py
mergify_cli/tests/ci_issues/test_junit_upload.py

`console.log` may wrap or add some whitespaces at end of the annotation.

fix: use console print instead of log for annotation

---

mergify_cli/cli.py
mergify_cli/stack/cli.py

Global options `--token` and `--github-server` are related to the `stack` group and should not have their defaults computed for other groups since they may break others commands.
--debug is still a global option:
$ `mergify --debug stack push`
This does not work anymore:
$ `mergify --token foobar stack push`
Global `stack` options are to be passed like this:
$ `mergify stack --token foobar push`

fix: put some default options to stack group

---

mergify_cli/ci/junit.py
mergify_cli/ci/upload.py
mergify_cli/tests/ci/test_junit.py

Do not use different traces for multiple JUnit

fix: make sure a single trace id is used for a single upload

---

mergify_cli/ci/upload.py
mergify_cli/tests/ci/test_upload.py

fix: do not raise error on upload failure

---

mergify_cli/ci/junit.py
mergify_cli/ci/upload.py
mergify_cli/tests/ci/test_junit.py

OpenTelemetry cannot encode 8 bytes integer in protobuf.

fix: set test.run.id as str

---

mergify_cli/ci/junit.py
mergify_cli/tests/ci/test_junit.py

refactor: set correct status name

---

mergify_cli/ci/cli.py

It will allow for easier testing and refactor of the command name in the
future.

refactor: move content of `junit_upload` command to its own function
